FROM node:18-alpine AS builder

WORKDIR /app

# Copier les fichiers package.json et package-lock.json pour installer les dépendances
COPY ../../package.json ../../package-lock.json ./
RUN npm install

# Copier le reste du code de l'application
COPY . .

# Définir les variables d'environnement
ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED=1

# Construire l'application Next.js
RUN npm run build

# Étape de production
FROM node:18-alpine AS runner

WORKDIR /app

# Copier uniquement les fichiers nécessaires pour exécuter l'application
COPY --from=builder /app/package.json /app/package-lock.json ./
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/next.config.js ./

# Installer uniquement les dépendances de production
RUN npm install --only=production

# Exposer le port sur lequel l'application s'exécute
EXPOSE 3000

# Démarrer l'application Next.js
CMD ["npm", "start"]