networks:
  back:
    name: "back"

services:
  nextjs:
    build:
      context: ..
      dockerfile: docker-compose-workshop/Dockerfile-nextjs-dev
    container_name: NextJS
    ports:
      - "3000:3000"
    volumes:
      - ../:/app
      - /app/node_modules
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:4000"
      NEXT_SERVER_API_URL: "http://api:4000"
      ## Variable d'environnement pour forcer le polling sur les fichiers du projet pour le hot-reload
      ## Fichier next.config.mjs à la racine du projet a été modifié pour prendre en compte cette variable
      CHOKIDAR_USEPOLLING: "true"
    networks:
      - back
